# Generated by Django 2.2.6 on 2019-11-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Category's name")),
                ('article', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name="Icon's name")),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Judge's name")),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Court's title")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.City')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('registry_number', models.IntegerField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, verbose_name='Case number')),
                ('url', models.URLField()),
                ('case_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('color', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('case_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.City')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Category')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Court')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Icon')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Judge')),
            ],
        ),
    ]
