# Generated by Django 3.1.1 on 2020-09-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name="Icon's name")),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('registry_number', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('case_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('color', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.icon')),
            ],
        ),
    ]
